---
functional:
  - возможность зарегистрироваться на сервисе с помощью простого ввода (email и пароль) или GitHub, или Discord 
  - возможность авторизиороваться с помощью предложенных вариантов (ввод email и пароль при регистрации или GitHub, или Discord
  - возможность без регистрации и авторизации в сервисе подключиться к лобби 
  - возможность после авторизации создать игру с выбором сложности, опонентов, лимита времени и задания  
  - возможность просмотра лидерборда (неделя, месяц и за всё время) 
  - возможность просмотра законченных игр других пользователей 
  - возможность просмотра повтора батлов  
  - возможность создания турниров и турнирной сетки с параметрами - название, количеством участников (одиночный, командный или лестница), доступ (публичный или нет), текущее время, уровень сложности, лимит игроков, лимит времени, предпочитаемый язык программирования 
  - возможность подключения к игре через раздел лобби 
  - возможность писать код после создания батла 
  - возможность выбора языка программирования после создания батла 
  - возможность сдаться после создания батла 
  - возможность очистить поле написанного кода после создания батла 
  - возможность запустить проверку после создания батла 
  - возможность видеть код, язык программирования, имя соперника
  - возможность открыть историю происходящего после окончания батла 
  - возможность вернуться на главное меню с лобби, турниром, завершенных игр, лидерборда и создания игры после перехода из завершенного батла
  - возможность переписываться в чате во время батла и после окончания (но до выхода из батла) 
  - возможность после определения победителя батла остаться и продолжить создавать код
  - возможность других пользователей следить за ходом игры 
  - пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время 
  - возможность сделать вылогин
  - возможность входа в свой личный профиль со статистикой рейтинга и завершенными играми 
non-functional:
  - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - после создания батла задание будет отображаться в разделе Task 
  - после авторизации в сервисе, появляется окно, которое говорит, что авторизация прошла успешно 
  - возможность просмотра игроков online
  - участник не может менять код соперника 
  - участники не могут менять задание при создании батла 
  - отправка запроса на воспроизведение звука при поражении в батле 
